### ISSUE TITLE
Article 5: Are there any other membership obligations?

### ISSUE THREAD

**Issue by goxberry** [jbardhan/csgf-draftdocs#12]
Such as some sort of attendance or participation requirements? If there aren't, then I don't think anything else needs to be added.

**Comment by jbardhan** [comment]
If my memory is correct, the tone of early discussions seemed to lean against obligations.\* 

*Disclaimer goes here

**Comment by jbardhan** [comment]
Hi @goxberry 

We discussed this and decided against writing in obligations at this time. The board may add them as necessary at a later date.

Thanks very much,
Jay
