### ISSUE TITLE
Article 3.  Separate sections to define member, board member, officers

### ISSUE THREAD

**Issue by ktchu** [jbardhan/csgf-draftdocs#14]
I think it would be helpful to organize Article 3 into separate sections that define the roles and responsibilities of members, board members, and officers.

**Comment by jbardhan** [comment]
Hi @ktchu ,

We agree and have reorganized Articles 3-5 to separate these positions and roles.  Does the revision address your concerns?

Thanks very much,
Jay

**Comment by ktchu** [comment]
Looks good.

-Kevin
