### ISSUE TITLE
Article 3.8.  Clarify first sentence.

### ISSUE THREAD

**Issue by ktchu** [jbardhan/csgf-draftdocs#15]
- Article 3.8 starts "If required by the Board, the Treasurer shall give a bond, at the expense of the Corporation, for faithful discharge of his or her duties in such sum and with such sureties as determined by the Board."  I find this sentence a little confusing.  Who is recipient of bond?
- Perhaps this sentence could be moved to a sub-item of a section defining the role and responsibilities for the Treasurer.

**Comment by jbardhan** [comment]
Hi @ktchu 

This sentence was boilerplate and doesn't seem to offer much for us, so it has been removed.

Thanks very much,
Jay
