### ISSUE TITLE
How are President, Secretary and Treasurer positions selected?

### ISSUE THREAD

**Issue by ktchu** [jbardhan/csgf-draftdocs#18]
From the seven board members, how are the positions of president, secretary and treasurer filled?  Are they appointed by the board members, elected by the voting members, etc?

**Comment by jbardhan** [comment]
Hi @ktchu 

Thanks for this catch.  We have specified it in Section 5.2 now.  Does this address your concerns?

Thanks very much,
Jay

**Comment by ktchu** [comment]
Works for me.

-Kevin
