### ISSUE TITLE
I needed an account to post this comment

### ISSUE THREAD

**Issue by ellio167** [jbardhan/csgf-draftdocs#2]
I thought that would not be needed. :-)

**Comment by jbardhan** [comment]
Sorry Ryan!  Easiest free infrastructure we could find =)

**Comment by ellio167** [comment]
Jay!  No problem.  I certainly have had a github account for some time...  I 
just wanted to make sure the board knew that this was the case; especially 
since the email announcement specifically said otherwise...

Cheers,

Ryan

On Mon, 21 Dec 2015, Jaydeep Bardhan wrote:

> Sorry Ryan!  Easiest free infrastructure we could find =)
> 
> On Sat, Dec 19, 2015 at 6:29 PM, Ryan S. Elliott notifications@github.com
> wrote:
> 
> > I thought that would not be needed. :-)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jbardhan/csgf-draftdocs/issues/2.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jbardhan/csgf-draftdocs/issues/2#issuecomment-166456014

## 

Ryan S. Elliott, Ph.D. and Associate Professor
Aerospace Engineering & Mechanics, University of Minnesota
(612) 624-2376 (626-1558 fax)
http://www.aem.umn.edu/~relliott/
download vCard http://www.aem.umn.edu/~relliott/relliott.vcf

KIM Editor (http://openKIM.org)
Associate Editor: Journal of Elasticity (http://springer.com/10659)
MSI Associate Fellow (http://msi.umn.edu)

## CMT textbook webpage (http://modelingmaterials.org)

[On Christopher Columbus's (later life) suggestion of a "pear-shaped"
    earth] ... The willingness to reexamine lifelong beliefs because of
    conflicting data takes enormous courage, and contrasts sharply with
    recent examples of public discourse in which our political, cultural,
    and religious leaders have fit data to preconceived theories.

```
                                                           Donal O'Shea
```

---
