### ISSUE TITLE
Definition of "The Corporation" needed?

### ISSUE THREAD

**Issue by ellio167** [jbardhan/csgf-draftdocs#3]
Things look very good, generally.  Thanks everyone!

The only thing that stands out to me is that the word "Corporation" creeps into the document without really being clear what it is referring to.  Before "Corporation" occurs the document uses the word "Association" in a similar context.

I wonder if there needs to be an item that explicitly says a corporation will be setup.

**Comment by hagberg** [comment]
@ellio167 makes a good point here.  Maybe the more general issue is choosing what legal structure this organization will have.  Has this been decided?  Does it generate some requirements for a constitution or bylaws?

**Comment by goxberry** [comment]
@hagberg According to _Robert's Rules of Order Newly Revised (11th edition)_ p. 13, ll. 10-25, the Name and Object of the organization are typically specified in a corporate charter, so the bylaws may change, depending on the order in which the organization is incorporated and the bylaws are adopted.

Also, according to _ibid._ p. 11, ll. 24-35 and p. 12, ll. 1-4, the corporate charter should:
- be drafted by an attorney
- can only be amended subject to applicable laws and provisions in the charter
- supersedes the bylaws
- nothing in it can be suspended except by provision of the charter

so a charter should only contain what is necessary to obtain it (name, object, legal status of organization) and leave everything else to the bylaws and lower-ranking rules, which are supposed to be easier to change.

As a separate point, in modern nonlegislative deliberative assemblies, constitution and bylaws tend to be combined (_ibid._, p. 12-14); the citation discusses reasons why combining them is preferable, and specifically notes (_ibid._, p. 14, ll. 6-9) that a constitution would duplicate much of the corporate charter.

**Comment by jbardhan** [comment]
Hi all,

We have elected to use the word "Association" throughout the document, and it is defined in Article 1.

Thanks very much,
Jay
