### ISSUE TITLE
Move bylaws to Markdown file in code so we can submit PRs

### ISSUE THREAD

**Issue by goxberry** [jbardhan/csgf-draftdocs#4]
I propose moving the bylaws to a Markdown file in the "code" section of this repository.

It is more expedient to make minor changes, or include suggested changes -- and properly credit the individual making those changes -- through a pull request mechanism. As it currently stands, such changes instead require posting an issue, followed by a separate change. Diffing GitHub wiki revisions is also clunky.

**Comment by goxberry** [comment]
Also, it enables citing revisions as commit hashes.

**Comment by jbardhan** [comment]
Great points, thanks.  Several aspects of this illustrate my ignorance of Github/Wiki/lots of other stuff.

Our aim at this stage was to spur discussion and de-emphasize direct edits.  Putting the bylaws in Markdown may well be the right move in future stages.

**Comment by goxberry** [comment]
@jbardhan No worries! I appreciate the bylaws being available on GitHub, and I appreciate the time and thought being put into them by you and the committee!
