### ISSUE TITLE
"two thirds vote" -> "two-thirds vote"

### ISSUE THREAD

**Issue by goxberry** [jbardhan/csgf-draftdocs#5]
In Article 7 of the 11th revision of the Bylaws, the sentence "These bylaws may be amended by a two thirds vote (of votes cast) by the voting members." should be changed to "These bylaws may be amended by a two-thirds vote (of votes cast) by the voting members."

The _Chicago Manual of Style_ suggests hyphenating simple fractions, and _Robert's Rules of Order Newly Revised (11th ed.)_ also hyphenates fractions when used as adjectives (specifically in phrases such as "two-thirds vote").

**Comment by jbardhan** [comment]
Done. Thanks for all these comments @goxberry!  When did you learn so much about RRONR?

**Comment by goxberry** [comment]
Bought a copy to make sure the bylaws are more solid because my mother has used it in the past for participating in board meetings (she's a member of the local school board, and other organizations).

**Comment by jbardhan** [comment]
Awesome.  Thank you for being so careful!
