### ISSUE TITLE
Article 2: Aspects of object of organization should be set off by semicolons

### ISSUE THREAD

**Issue by goxberry** [jbardhan/csgf-draftdocs#7]
"In unincorporated societies, the object of the society should be concisely expressed in a single sentence, the various aspects or phrases being written in sequence, set off by semicolons." -- _Robert's Rules of Order Newly Revised (11th ed.)_, p. 571, ll. 1-5.

Suggested revision:

"The purpose of the association shall be to join former CSGF fellows together in organized efforts to benefit members of the association and current CSGF fellows; to advocate for the CSGF program; and to advocate for computational science generally." (Possibly omit "generally", if the intention is to advocate for computational science as a subject. If the intention is to advocate for the computational science community, that should be stated as well.)

The object of the deliberative assembly is important, since apparently, a two-thirds vote is required to allow the introduction of a motion that falls outside the society's object. _ibid._, p. 571, ll. 5-9.

**Comment by jbardhan** [comment]
Thanks, the structure you suggest looks familiar from another organization I was part of.

**Comment by jbardhan** [comment]
We have made these changes!

Thanks very much,
Jay
