### ISSUE TITLE
Article 5: Members should be defined before officers

### ISSUE THREAD

**Issue by goxberry** [jbardhan/csgf-draftdocs#8]
Membership eligibility in the organization should be defined before officers are defined. The assumption in bylaws seems to be that officers must be members. _Robert's Rules of Order Newly Revised (11th ed.)_, p. 521, l. 20 suggests defining members in Article 3 (in _RONR_, Article III).

**Comment by jbardhan** [comment]
That makes a lot of sense. Thanks!

**Comment by jbardhan** [comment]
We have re-ordered these sections accordingly.

Thanks very much,
jay
