### ISSUE TITLE
Article 5: Set provisions off into sections.

### ISSUE THREAD

**Issue by goxberry** [jbardhan/csgf-draftdocs#9]
Provisions in Article 5 should be set off into sections. Suggested edit:

"1. Membership in the association is open to anyone who previously received funding through the CSGF program and is not a current Fellow.
1. Voting members are members who have paid dues to the association during the current calendar year."

**Comment by jbardhan** [comment]
As it's written right now, there isn't anything else so I don't understand why we would set points off into subsections.  Are you referencing the next issue, i.e. suspended memberships?

**Comment by jbardhan** [comment]
Hi @goxberry,

We have set these off as suggested.  Can you please confirm this was what was intended?

Thanks very much,
Jay

**Comment by goxberry** [comment]
@jbardhan Thank you for your patience! I envisioned only two levels of headings (Article, Section). I like the current organization, which incorporates additional levels (subsection, clause) while remaining readable. Great job!
